name: Test

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  format:
    name: Check formatting
    timeout-minutes: 25
    runs-on: "runs-on/runner=4cpu-linux-x64/run-id=${{ github.run_id }}"
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: step-security/mise-action@2796166110dee826668caddd4bffedae5116e7cd # v4.2.0
      - run: mix format --check-formatted
  test:
    name: Test
    runs-on: "runs-on/runner=4cpu-linux-x64/run-id=${{ github.run_id }}"
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: step-security/mise-action@2796166110dee826668caddd4bffedae5116e7cd # v4.2.0
      - uses: step-security/runs-on-cache@c5b0cba15d05488ebc630ad8d1e95b3d9b35ac73 # v5.0.7
        name: Cache dependencies
        with:
          path: |
            deps
          key: deps-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ hashFiles('mix.lock') }}
            deps-
      - run: mix deps.get
      - uses: step-security/runs-on-cache@c5b0cba15d05488ebc630ad8d1e95b3d9b35ac73 # v5.0.7
        name: Cache build
        with:
          path: |
            _build
          key: build-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            build-${{ runner.os }}-${{ hashFiles('mix.lock') }}
            build-${{ runner.os }}-
      - run: mix test

  dialyze:
    name: Dialyze
    runs-on: "runs-on/runner=4cpu-linux-x64/run-id=${{ github.run_id }}"
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: step-security/mise-action@2796166110dee826668caddd4bffedae5116e7cd # v4.2.0
      - uses: step-security/runs-on-cache@c5b0cba15d05488ebc630ad8d1e95b3d9b35ac73 # v5.0.7
        name: Cache dependencies
        with:
          path: |
            deps
          key: deps-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ hashFiles('mix.lock') }}
            deps-
      - run: mix deps.get
      - uses: step-security/runs-on-cache@c5b0cba15d05488ebc630ad8d1e95b3d9b35ac73 # v5.0.7
        name: Cache build
        with:
          path: |
            _build
          key: build-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            build-${{ runner.os }}-${{ hashFiles('mix.lock') }}
            build-${{ runner.os }}-
      - uses: step-security/runs-on-cache@c5b0cba15d05488ebc630ad8d1e95b3d9b35ac73 # v5.0.7
        name: Restore PLT cache
        id: plt_cache
        with:
          path: |
            priv/plts
          key: plt-${{ runner.os }}-${{ hashFiles('mise.toml') }}
          restore-keys: |
            plt-${{ runner.os }}-${{ hashFiles('mise.toml') }}
      - name: Create PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt
      - name: Run dialyzer
        run: mix dialyzer --format github
